import { StatsGrid } from "@/components/StatsGrid";
import { StatsRing } from "@/components/StatsRing";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cash D+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> 
       <section>
        <h1>Dashboard</h1>
        <StatsGrid />
        {/*<StatsRing />*/}
       </section>
      </main>
    </>
  );
}
